### ISSUE TITLE
Implement pattern for custom field types and nested fields

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/typehint-serialization-experiment#4]
I think something along these lines may be desirable, or even a more simplified version which relies on type hints in the schema field definitions - though I don't know if I want to expose the annotation definitions too much in general usage, probably better to keep that contained in the base library/custom field definitions.

Quick mockup:

```python
class UserModel:
    """User model"""
    user_id = Integer()
    user_name = String()


class UserModelField(Field):
    """Field definition"""
    value: UserModel = None


class UserSchema(Schema):
    ""Schema definition"""
    user = UserModelField()


schema = UserSchema()
```

**Comment by erm** [comment]
Introduced in https://github.com/erm/loamy/commit/0545f630374df73383c24b9a2bae43c6902bc5dc
